### ISSUE TITLE
Overseerr support

### ISSUE THREAD

**Issue by 2fst4u** [Cleanarr/Cleanarr#4]
**Describe the solution you'd like**
Really awesome idea! Any chance of overseerr support?

**Describe alternatives you've considered**
Ombi is ok but a lot of people are jumping ship to overseerr now.

**Additional context**
The ability to remove things after a requester has watched them is exactly what I need!

**Comment by lbarnett83** [comment]
Another +1 for this

**Comment by appiekap653** [comment]
Yes! Overseerr is definitely on the menu. I will try to write as many plugins possible beforehand and overseerr will be one of them. To make this as open as possible there will be an option for everyone to create their own plugins to support even more different software as media servers, histories providers and request providers.
